### ISSUE TITLE
Image can't be uploaded

### ISSUE THREAD

**Issue by KalleChen** [CAMPUS-NYCU/SmartCampus#82]
## **Describe the bug**
Image upload faild

## **Steps To Reproduce**
1. Upload tag
2. Choose an image
3. Click submit
4. See an error

## **Expected behavior**
The image uploading process should succeed

**Comment by stvreumi** [comment]
Need to activate `Service Account Token Creator` role in both `@developer.gserviceaccount.com` and `@cloudservices.gserviceaccount.com` service account.
See this [issue](https://github.com/googleapis/nodejs-storage/issues/1222).
This has been fixed by adding `Service Account Token Creator` role to the service accounts.
